alter table UNIVERSITY_STUDENT add constraint FK_UNIVERSITY_STUDENT_ON_GROUP foreign key (GROUP_ID) references UNIVERSITY_GROUP(ID);
create index IDX_UNIVERSITY_STUDENT_ON_GROUP on UNIVERSITY_STUDENT (GROUP_ID);
